# Generated by Django 5.1.7 on 2025-04-07 20:04

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='meals/')),
                ('our_meals_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='meals/')),
            ],
            options={
                'verbose_name': 'Meals Page Content',
                'verbose_name_plural': 'Meals Page Content',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnimalSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=50)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.service')),
            ],
            options={
                'verbose_name': 'Prices',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='MealsPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('hero_title', models.CharField(default='Nutritious Meals for Your Pets', max_length=100, verbose_name='Hero Title')),
                ('hero_subheading', models.CharField(default="Delicious, healthy options tailored to your pet's needs.", max_length=255, verbose_name='Hero Subheading')),
                ('our_meals_title', models.CharField(default='Deliciously Tailored', max_length=100, verbose_name='Our Meals Title')),
                ('our_meals_subheading', models.TextField(default='We offer a variety of nutritious meals for dogs and cats, tailored by size and dietary requirements.', verbose_name='Our Meals Subheading')),
                ('meals_info_title', models.CharField(default='Meal Options & Pricing', max_length=100, verbose_name='Meals Info Title')),
                ('meals_info_description', models.TextField(default='From premium kibble to gourmet cooked meals, we cater to all sizes and breeds. Pricing varies based on animal size.', verbose_name='Meals Info Description')),
                ('cta_title', models.CharField(default='Ready to Treat Your Pet?', max_length=100, verbose_name='CTA Title')),
                ('cta_subheading', models.TextField(default="Book your pet's stay and include their favorite meals today.", verbose_name='CTA Subheading')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='meals.mealspage')),
            ],
            options={
                'verbose_name': 'Meals Page Content Translation',
                'db_table': 'meals_mealspage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='meals.service')),
            ],
            options={
                'verbose_name': 'Services Translation',
                'db_table': 'meals_service_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
