# Generated by Django 5.1.7 on 2025-04-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalsize',
            name='animal',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], max_length=50),
        ),
        migrations.AlterField(
            model_name='animalsize',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50),
        ),
    ]
