# Generated by Django 5.1.7 on 2025-04-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_animalsize_animal_alter_animalsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalsize',
            name='animal',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=50),
        ),
    ]
