# Generated by Django 5.1.7 on 2025-04-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_animalsize_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Nutritious Meals for Your Pets', max_length=100)),
                ('hero_subheading', models.CharField(default="Delicious, healthy options tailored to your pet's needs.", max_length=255)),
                ('hero_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='meals/')),
                ('our_meals_title', models.CharField(default='Deliciously Tailored', max_length=100)),
                ('our_meals_subheading', models.TextField(default='We offer a variety of nutritious meals for dogs and cats, tailored by size and dietary requirements.')),
                ('our_meals_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='meals/')),
                ('meals_info_title', models.CharField(default='Meal Options & Pricing', max_length=100)),
                ('meals_info_description', models.TextField(default='From premium kibble to gourmet cooked meals, we cater to all sizes and breeds. Pricing varies based on animal size.')),
                ('cta_title', models.CharField(default='Ready to Treat Your Pet?', max_length=100)),
                ('cta_subheading', models.TextField(default="Book your pet's stay and include their favorite meals today.")),
            ],
            options={
                'verbose_name': 'Meals Page',
                'verbose_name_plural': 'Meals Page',
            },
        ),
    ]
