# Generated by Django 5.1.7 on 2025-04-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_animalsize_options_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealspage',
            options={'verbose_name': 'Meals Page Content', 'verbose_name_plural': 'Meals Page Content'},
        ),
    ]
