# Generated by Django 5.1.7 on 2025-04-07 20:04

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Prices',
                'verbose_name_plural': 'Prices',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WaterSportsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='water_sports/')),
                ('our_watersports_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='water_sports/')),
            ],
            options={
                'verbose_name': 'WaterSports Page Content',
                'verbose_name_plural': 'WaterSports Page Content',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='water_sports.service')),
            ],
            options={
                'verbose_name': 'Prices Translation',
                'db_table': 'water_sports_service_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WaterSportsPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('hero_title', models.CharField(default='Exciting Dog Water Sports Adventures', max_length=100, verbose_name='Hero Title')),
                ('hero_subheading', models.CharField(default='Dive into fun with safe, guided aquatic activities designed for dogs of all sizes and skill levels.', max_length=255, verbose_name='Hero Subheading')),
                ('our_watersports_title', models.CharField(default='Fun & Safe Water Activities', max_length=100, verbose_name='Our Water Sports Title')),
                ('our_watersports_subheading', models.TextField(default='From paddle boarding and dock diving to swim training, our experienced team ensures your pup enjoys the water with confidence.', verbose_name='Our Water Sports Subheading')),
                ('watersports_info_title', models.CharField(default='Activities & Packages', max_length=100, verbose_name='Water Sports Info Title')),
                ('watersports_info_description', models.TextField(default='Choose from single-day experiences to multi-session packages. All activities are supervised and tailored to your dog’s comfort and ability level.', verbose_name='Water Sports Info Description')),
                ('cta_title', models.CharField(default='Make a Splash with Us!', max_length=100, verbose_name='CTA Title')),
                ('cta_subheading', models.TextField(default="Book a session today and give your dog the ultimate water adventure. Spots fill fast, so don't miss out!", verbose_name='CTA Subheading')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='water_sports.watersportspage')),
            ],
            options={
                'verbose_name': 'WaterSports Page Content Translation',
                'db_table': 'water_sports_watersportspage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
