# Generated by Django 5.1.7 on 2025-04-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Prices', 'verbose_name_plural': 'Prices'},
        ),
    ]
