# Generated by Django 5.1.7 on 2025-04-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_sports', '0002_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSportsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Exciting Dog Water Sports Adventures', max_length=100)),
                ('hero_subheading', models.CharField(default='Dive into fun with safe, guided aquatic activities designed for dogs of all sizes and skill levels.', max_length=255)),
                ('hero_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='water_sports/')),
                ('our_training_title', models.CharField(default='Fun & Safe Water Activities', max_length=100)),
                ('our_training_subheading', models.TextField(default='From paddle boarding and dock diving to swim training, our experienced team ensures your pup enjoys the water with confidence.')),
                ('our_training_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='water_sports/')),
                ('training_info_title', models.CharField(default='Activities & Packages', max_length=100)),
                ('training_info_description', models.TextField(default='Choose from single-day experiences to multi-session packages. All activities are supervised and tailored to your dog’s comfort and ability level.')),
                ('cta_title', models.CharField(default='Make a Splash with Us!', max_length=100)),
                ('cta_subheading', models.TextField(default="Book a session today and give your dog the ultimate water adventure. Spots fill fast, so don't miss out!")),
            ],
            options={
                'verbose_name': 'WaterSports Page Content',
                'verbose_name_plural': 'WaterSports Page Content',
            },
        ),
    ]
