# Generated by Django 5.1.7 on 2025-04-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_sports', '0003_watersportspage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watersportspage',
            old_name='our_training_image',
            new_name='our_watersports_image',
        ),
        migrations.RenameField(
            model_name='watersportspage',
            old_name='our_training_title',
            new_name='our_watersports_title',
        ),
        migrations.RenameField(
            model_name='watersportspage',
            old_name='training_info_description',
            new_name='watersports_info_description',
        ),
        migrations.RenameField(
            model_name='watersportspage',
            old_name='training_info_title',
            new_name='watersports_info_title',
        ),
    ]
