# Generated by Django 5.1.7 on 2025-04-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_sports', '0004_rename_our_training_image_watersportspage_our_watersports_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watersportspage',
            old_name='our_training_subheading',
            new_name='our_watersports_subheading',
        ),
    ]
