# Generated by Django 5.1.7 on 2025-04-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subheading', models.TextField()),
                ('hero_image', models.ImageField(upload_to='about/')),
                ('our_story_title', models.CharField(max_length=200)),
                ('our_story_subheading', models.TextField()),
                ('our_story_image', models.ImageField(upload_to='about/')),
                ('our_mission_title', models.CharField(max_length=200)),
                ('our_mission_subheading', models.TextField()),
                ('our_mission_image', models.ImageField(upload_to='about/')),
                ('our_team_title', models.CharField(max_length=200)),
                ('our_team_subheading', models.TextField()),
                ('our_team_image', models.ImageField(upload_to='about/')),
                ('our_commitment_title', models.CharField(max_length=200)),
                ('our_commitment_subheading', models.TextField()),
                ('our_commitment_image', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
