# Generated by Django 5.1.7 on 2025-04-07 20:04

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(default='default/placeholder.jpg', upload_to='about/')),
                ('our_story_image', models.ImageField(default='default/placeholder.jpg', upload_to='about/')),
                ('our_mission_image', models.ImageField(default='default/placeholder.jpg', upload_to='about/')),
                ('our_team_image', models.ImageField(default='default/placeholder.jpg', upload_to='about/')),
                ('our_commitment_image', models.ImageField(default='default/placeholder.jpg', upload_to='about/')),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('hero_title', models.CharField(default='About Us', max_length=200)),
                ('hero_subheading', models.TextField(default='Where every paw is pampered and every whisker welcomed. Experience exceptional care in a serene, home-away-from-home setting.')),
                ('our_story_title', models.CharField(default='Our Story', max_length=200)),
                ('our_story_subheading', models.TextField(default='What began as a dream to create the perfect haven for pets quickly became a reality. Built on love, trust, and comfort, our space is designed to offer pets a holiday of their own.')),
                ('our_mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('our_mission_subheading', models.TextField(default='To provide a tranquil and enriching environment where pets are nurtured, loved, and treated with the utmost care — every single day.')),
                ('our_team_title', models.CharField(default='Meet the Team', max_length=200)),
                ('our_team_subheading', models.TextField(default='A passionate team of animal lovers, professional caregivers, and trained staff, all dedicated to making pets feel safe, happy, and right at home.')),
                ('our_commitment_title', models.CharField(default='Our Commitment', max_length=200)),
                ('our_commitment_subheading', models.TextField(default='We’re devoted to setting a new standard in pet hospitality — luxurious spaces, personalized care, and a loving environment for every furry guest.')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.aboutpage')),
            ],
            options={
                'verbose_name': 'About Page Content Translation',
                'db_table': 'about_aboutpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
