# Generated by Django 5.1.7 on 2025-04-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_subheading',
            field=models.TextField(default='A luxurious escape for your beloved companions. Where comfort, care, and cuddles come standard.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(default='Welcome to Paws & Whiskers Retreat', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_commitment_subheading',
            field=models.TextField(default='We’re committed to redefining pet hospitality — offering unmatched comfort, health-first facilities, and heartwarming service that keeps tails wagging and whiskers twitching.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_commitment_title',
            field=models.CharField(default='Our Commitment', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_mission_subheading',
            field=models.TextField(default='To provide a safe, soothing, and stimulating environment where pets are pampered and their humans find peace of mind. Every stay is tailored, every guest treated like royalty.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_mission_title',
            field=models.CharField(default='Our Mission', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_story_subheading',
            field=models.TextField(default='Born from a deep love for animals and a passion for premium hospitality, Paws & Whiskers Retreat was founded to give pets a vacation of their own. Every suite, treat, and tail wag is part of a story built on trust and compassion.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_story_title',
            field=models.CharField(default='Our Story', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_team_subheading',
            field=models.TextField(default='From certified groomers to experienced caretakers and cuddly concierge staff, our dedicated team ensures every pet receives top-tier care and endless love.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_team_title',
            field=models.CharField(default='Meet Our Team', max_length=200),
        ),
    ]
