# Generated by Django 5.1.7 on 2025-04-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutpage_hero_subheading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_image',
            field=models.ImageField(default='default/placeholder.jpg', upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_commitment_image',
            field=models.ImageField(default='default/placeholder.jpg', upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_mission_image',
            field=models.ImageField(default='default/placeholder.jpg', upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_story_image',
            field=models.ImageField(default='default/placeholder.jpg', upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_team_image',
            field=models.ImageField(default='default/placeholder.jpg', upload_to='about/'),
        ),
    ]
