# Generated by Django 5.1.7 on 2025-04-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutpage_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_subheading',
            field=models.TextField(default='Where every paw is pampered and every whisker welcomed. Experience exceptional care in a serene, home-away-from-home setting.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(default='A Luxury Retreat for Your Beloved Pets', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_commitment_subheading',
            field=models.TextField(default='We’re devoted to setting a new standard in pet hospitality — luxurious spaces, personalized care, and a loving environment for every furry guest.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_mission_subheading',
            field=models.TextField(default='To provide a tranquil and enriching environment where pets are nurtured, loved, and treated with the utmost care — every single day.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_story_subheading',
            field=models.TextField(default='What began as a dream to create the perfect haven for pets quickly became a reality. Built on love, trust, and comfort, our space is designed to offer pets a holiday of their own.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_team_subheading',
            field=models.TextField(default='A passionate team of animal lovers, professional caregivers, and trained staff, all dedicated to making pets feel safe, happy, and right at home.'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_team_title',
            field=models.CharField(default='Meet the Team', max_length=200),
        ),
    ]
