# Generated by Django 5.1.7 on 2025-04-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_aboutpage_hero_subheading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(default='About Us', max_length=200),
        ),
    ]
