# Generated by Django 5.1.7 on 2025-04-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_aboutpage_hero_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About Page', 'verbose_name_plural': 'About Page'},
        ),
    ]
