# Generated by Django 5.1.7 on 2025-04-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_aboutpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About Page Content', 'verbose_name_plural': 'About Page Content'},
        ),
    ]
