# Generated by Django 5.1.7 on 2025-04-03 15:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_video', models.FileField(default='default/about_video.mp4', help_text='Upload the about section video.', upload_to='home_page/videos/')),
                ('about_title_video', models.FileField(default='default/about_title_video.mp4', help_text='Upload the about section title video.', upload_to='home_page/videos/')),
                ('services_title_video', models.FileField(default='default/services_title_video.mp4', help_text='Upload the services section title video.', upload_to='home_page/videos/')),
                ('strategy_title_video', models.FileField(default='default/strategy_title_video.mp4', help_text='Upload the strategy section title video.', upload_to='home_page/videos/')),
                ('strategy_video', models.FileField(default='default/strategy_video.mp4', help_text='Upload the strategy section video.', upload_to='home_page/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
        ),
    ]
