# Generated by Django 5.1.7 on 2025-04-07 20:04

import django.db.models.deletion
import django_ckeditor_5.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default='default/placeholder.mp4', help_text='Upload the walkaround video.', upload_to='home_page/')),
                ('hero_image', models.ImageField(default='default/placeholder.jpg', help_text='Upload the hero section background image.', upload_to='home_page/')),
                ('about_image', models.ImageField(default='default/placeholder.jpg', help_text='Upload the about section image.', upload_to='home_page/')),
                ('location_image', models.ImageField(default='default/placeholder.jpg', help_text='Upload the location section image.', upload_to='home_page/')),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrivacyPolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Privacy Policy Content',
                'verbose_name_plural': 'Privacy Policy Content',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TermsOfServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Terms Of Service Page Content',
                'verbose_name_plural': 'Terms Of Service Page Content',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomePageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('hero_title', models.CharField(default='Unmatched Comfort for Your Pet', help_text='Main title for the hero section.', max_length=100)),
                ('hero_subheading', models.CharField(default='A peaceful, luxury stay designed for ultimate relaxation, fun, and pampering.', help_text='Subheading text for the hero section.', max_length=255)),
                ('about_title', models.CharField(default='A Place Designed With Pets in Mind', help_text='Title for the about section.', max_length=100)),
                ('about_subheading', models.CharField(default='Every corner crafted for safety, joy, and serenity — because they deserve the best.', help_text='Subheading for the about section.', max_length=255)),
                ('promise_title', models.CharField(default='Our Promise to You', help_text="Title for the 'Our Promise' section.", max_length=100)),
                ('promise_subheading', models.CharField(default='Compassionate care, luxurious surroundings, and attention to every detail of your pet’s stay.', help_text="Subheading for the 'Our Promise' section.", max_length=255)),
                ('lifestyle_title', models.CharField(default='The Lifestyle They Deserve', help_text='Title for the lifestyle section.', max_length=100)),
                ('lifestyle_subheading', models.CharField(default='Spacious play areas, gourmet meals, spa treatments, and cozy naps — it’s more than a stay, it’s a lifestyle.', help_text='Subheading for the lifestyle section.', max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Home Page Content Translation',
                'db_table': 'home_homepage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrivacyPolicyPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.privacypolicypage')),
            ],
            options={
                'verbose_name': 'Privacy Policy Content Translation',
                'db_table': 'home_privacypolicypage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TermsOfServicePageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.termsofservicepage')),
            ],
            options={
                'verbose_name': 'Terms Of Service Page Content Translation',
                'db_table': 'home_termsofservicepage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
