# Generated by Django 5.1.7 on 2025-04-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_title_video',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_video',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services_title_video',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='strategy_title_video',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='strategy_video',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_image',
            field=models.ImageField(default='default/about-image.jpg', help_text='Upload the about section image.', upload_to='home_page/images/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(default='default/hero-image.jpg', help_text='Upload the hero section background image.', upload_to='home_page/images/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='location_image',
            field=models.ImageField(default='default/location-image.jpg', help_text='Upload the location section image.', upload_to='home_page/images/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video',
            field=models.FileField(default='default/video.mp4', help_text='Upload the walkaround video.', upload_to='home_page/videos/'),
        ),
    ]
