# Generated by Django 5.1.7 on 2025-04-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_homepage_about_title_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_subheading',
            field=models.CharField(default=1, help_text='Subheading for the about section.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(default=1, help_text='Title for the about section.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subheading',
            field=models.CharField(default=1, help_text='Subheading text for the hero section.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default=1, help_text='Main title for the hero section.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='lifestyle_subheading',
            field=models.CharField(default=1, help_text='Subheading for the lifestyle section.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='lifestyle_title',
            field=models.CharField(default=1, help_text='Title for the lifestyle section.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='promise_subheading',
            field=models.CharField(default=1, help_text="Subheading for the 'Our Promise' section.", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='promise_title',
            field=models.CharField(default=1, help_text="Title for the 'Our Promise' section.", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_image',
            field=models.ImageField(help_text='Upload the about section image.', upload_to='home_page/images/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(help_text='Upload the hero section background image.', upload_to='home_page/images/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='location_image',
            field=models.ImageField(help_text='Upload the location section image.', upload_to='home_page/images/'),
        ),
    ]
