# Generated by Django 5.1.7 on 2025-04-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_about_subheading_homepage_about_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_image',
            field=models.ImageField(default='default/placeholder.jpg', help_text='Upload the about section image.', upload_to='home_page/images/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_subheading',
            field=models.CharField(default='Every corner crafted for safety, joy, and serenity — because they deserve the best.', help_text='Subheading for the about section.', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(default='A Place Designed With Pets in Mind', help_text='Title for the about section.', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(default='default/placeholder.jpg', help_text='Upload the hero section background image.', upload_to='home_page/images/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subheading',
            field=models.CharField(default='A peaceful, luxury stay designed for ultimate relaxation, fun, and pampering.', help_text='Subheading text for the hero section.', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Unmatched Comfort for Your Pet', help_text='Main title for the hero section.', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='lifestyle_subheading',
            field=models.CharField(default='Spacious play areas, gourmet meals, spa treatments, and cozy naps — it’s more than a stay, it’s a lifestyle.', help_text='Subheading for the lifestyle section.', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='lifestyle_title',
            field=models.CharField(default='The Lifestyle They Deserve', help_text='Title for the lifestyle section.', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='location_image',
            field=models.ImageField(default='default/placeholder.jpg', help_text='Upload the location section image.', upload_to='home_page/images/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promise_subheading',
            field=models.CharField(default='Compassionate care, luxurious surroundings, and attention to every detail of your pet’s stay.', help_text="Subheading for the 'Our Promise' section.", max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promise_title',
            field=models.CharField(default='Our Promise to You', help_text="Title for the 'Our Promise' section.", max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='video',
            field=models.FileField(default='default/placeholder.mp4', help_text='Upload the walkaround video.', upload_to='home_page/videos/'),
        ),
    ]
