# Generated by Django 5.1.7 on 2025-04-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_about_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_image',
            field=models.ImageField(default='default/placeholder.jpg', help_text='Upload the about section image.', upload_to='home_page/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(default='default/placeholder.jpg', help_text='Upload the hero section background image.', upload_to='home_page/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='location_image',
            field=models.ImageField(default='default/placeholder.jpg', help_text='Upload the location section image.', upload_to='home_page/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='video',
            field=models.FileField(default='default/placeholder.mp4', help_text='Upload the walkaround video.', upload_to='home_page/'),
        ),
    ]
