# Generated by Django 5.1.7 on 2025-04-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_about_image_alter_homepage_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Page'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicypage',
            options={'verbose_name': 'Privacy Policy', 'verbose_name_plural': 'Privacy Policy'},
        ),
        migrations.AlterModelOptions(
            name='termsofservicepage',
            options={'verbose_name': 'Terms Of Service', 'verbose_name_plural': 'Terms Of Service'},
        ),
    ]
