# Generated by Django 5.1.7 on 2025-04-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page Content', 'verbose_name_plural': 'Home Page Content'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicypage',
            options={'verbose_name': 'Privacy Policy Content', 'verbose_name_plural': 'Privacy Policy Content'},
        ),
        migrations.AlterModelOptions(
            name='termsofservicepage',
            options={'verbose_name': 'Terms Of Service Page Content', 'verbose_name_plural': 'Terms Of Service Page Content'},
        ),
    ]
