# Generated by Django 5.1.7 on 2025-04-07 14:21

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='grooming/')),
                ('our_grooming_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='grooming/')),
            ],
            options={
                'verbose_name': 'Grooming Page Content',
                'verbose_name_plural': 'Grooming Page Content',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnimalSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=50)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grooming.service')),
            ],
            options={
                'verbose_name': 'Prices',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='GroomingPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('hero_title', models.CharField(default='Professional Pet Grooming Services', max_length=100)),
                ('hero_subheading', models.CharField(default='Keep your furry friend looking and feeling their best with our expert grooming care.', max_length=255)),
                ('our_grooming_title', models.CharField(default='Tailored Grooming for Every Pet', max_length=100)),
                ('our_grooming_subheading', models.TextField(default='We provide breed-specific grooming, coat care, and spa treatments designed to suit your pet’s individual needs.')),
                ('grooming_info_title', models.CharField(default='Grooming Packages & Pricing', max_length=100)),
                ('grooming_info_description', models.TextField(default='Choose from full-service grooms, quick clean-ups, or luxury spa packages. Pricing depends on pet size, coat type, and selected services.')),
                ('cta_title', models.CharField(default='Time for a Fresh Look?', max_length=100)),
                ('cta_subheading', models.TextField(default='Schedule your pet’s grooming session today and give them the pampering they deserve.')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='grooming.groomingpage')),
            ],
            options={
                'verbose_name': 'Grooming Page Content Translation',
                'db_table': 'grooming_groomingpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='grooming.service')),
            ],
            options={
                'verbose_name': 'Services Translation',
                'db_table': 'grooming_service_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
