# Generated by Django 5.1.7 on 2025-04-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0002_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('animal', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], max_length=3)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='AnimalSize',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
