# Generated by Django 5.1.7 on 2025-04-01 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0003_groomingservice_delete_animalsize_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], max_length=3)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='GroomingService',
        ),
        migrations.AddField(
            model_name='animalsize',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grooming.service'),
        ),
    ]
