# Generated by Django 5.1.7 on 2025-04-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0004_animalsize_service_delete_groomingservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalsize',
            name='animal',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=50),
        ),
        migrations.AlterField(
            model_name='animalsize',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50),
        ),
    ]
