# Generated by Django 5.1.7 on 2025-04-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0005_alter_animalsize_animal_alter_animalsize_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalsize',
            options={'verbose_name': 'Prices', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
    ]
