# Generated by Django 5.1.7 on 2025-04-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0006_alter_animalsize_options_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Professional Pet Grooming Services', max_length=100)),
                ('hero_subheading', models.CharField(default='Keep your furry friend looking and feeling their best with our expert grooming care.', max_length=255)),
                ('hero_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='grooming/')),
                ('our_grooming_title', models.CharField(default='Tailored Grooming for Every Pet', max_length=100)),
                ('our_grooming_subheading', models.TextField(default='We provide breed-specific grooming, coat care, and spa treatments designed to suit your pet’s individual needs.')),
                ('our_grooming_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='grooming/')),
                ('grooming_info_title', models.CharField(default='Grooming Packages & Pricing', max_length=100)),
                ('grooming_info_description', models.TextField(default='Choose from full-service grooms, quick clean-ups, or luxury spa packages. Pricing depends on pet size, coat type, and selected services.')),
                ('cta_title', models.CharField(default='Time for a Fresh Look?', max_length=100)),
                ('cta_subheading', models.TextField(default='Schedule your pet’s grooming session today and give them the pampering they deserve.')),
            ],
            options={
                'verbose_name': 'Grooming Page Content',
                'verbose_name_plural': 'Grooming Page Content',
            },
        ),
    ]
