# Generated by Django 5.1.7 on 2025-04-07 20:04

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Prices',
                'verbose_name_plural': 'Prices',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TrainingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='training/')),
                ('our_training_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='training/')),
            ],
            options={
                'verbose_name': 'Training Page Content',
                'verbose_name_plural': 'Training Page Content',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='training.service')),
            ],
            options={
                'verbose_name': 'Prices Translation',
                'db_table': 'training_service_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TrainingPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('hero_title', models.CharField(default='Expert Dog Training Services', max_length=100, verbose_name='Hero Title')),
                ('hero_subheading', models.CharField(default="Professional, compassionate training tailored to your dog's behavior and needs.", max_length=255, verbose_name='Hero Subheading')),
                ('our_training_title', models.CharField(default='Personalized Dog Training', max_length=100, verbose_name='Our Training Title')),
                ('our_training_subheading', models.TextField(default='From basic obedience to advanced behavioral correction, our trainers work with dogs of all breeds and sizes.', verbose_name='Our Training Subheading')),
                ('training_info_title', models.CharField(default='Training Programs & Pricing', max_length=100, verbose_name='Training Info Title')),
                ('training_info_description', models.TextField(default='We offer flexible programs including group classes, private sessions, and intensive boot camps. Pricing depends on program type and duration.', verbose_name='Training Info Description')),
                ('cta_title', models.CharField(default='Ready to Train Your Dog?', max_length=100, verbose_name='CTA Title')),
                ('cta_subheading', models.TextField(default='Book a consultation today and start your dog’s journey to better behavior and obedience.', verbose_name='CTA Subheading')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='training.trainingpage')),
            ],
            options={
                'verbose_name': 'Training Page Content Translation',
                'db_table': 'training_trainingpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
