# Generated by Django 5.1.7 on 2025-04-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Expert Dog Training Services', max_length=100)),
                ('hero_subheading', models.CharField(default="Professional, compassionate training tailored to your dog's behavior and needs.", max_length=255)),
                ('hero_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='training/')),
                ('our_training_title', models.CharField(default='Personalized Dog Training', max_length=100)),
                ('our_training_subheading', models.TextField(default='From basic obedience to advanced behavioral correction, our trainers work with dogs of all breeds and sizes.')),
                ('our_training_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='training/')),
                ('training_info_title', models.CharField(default='Training Programs & Pricing', max_length=100)),
                ('training_info_description', models.TextField(default='We offer flexible programs including group classes, private sessions, and intensive boot camps. Pricing depends on program type and duration.')),
                ('cta_title', models.CharField(default='Ready to Train Your Dog?', max_length=100)),
                ('cta_subheading', models.TextField(default='Book a consultation today and start your dog’s journey to better behavior and obedience.')),
            ],
            options={
                'verbose_name': 'Training Page Content',
                'verbose_name_plural': 'Training Page Content',
            },
        ),
    ]
