# Generated by Django 5.1.7 on 2025-04-07 14:21

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='hotel/')),
                ('our_facilities_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='hotel/')),
                ('our_services_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='hotel/')),
                ('our_prices_subheading', models.TextField(default='Our exclusive accommodations provide comfort and luxury for your pet, ensuring a relaxing stay. Choose the best option for your furry companion and experience the finest care.')),
            ],
            options={
                'verbose_name': 'Hotel Page Content',
                'verbose_name_plural': 'Hotel Page Content',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_hotel_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='services/')),
                ('our_meal_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='services/')),
                ('our_training_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='services/')),
                ('our_grooming_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='services/')),
                ('our_watersports_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='services/')),
                ('our_transportation_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='services/')),
            ],
            options={
                'verbose_name': 'All Services Page Content',
                'verbose_name_plural': 'All Services Page Content',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HotelPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('hero_title', models.CharField(default='Your Pets Luxury Stay', max_length=255)),
                ('hero_subheading', models.TextField(default='Let Your Pet Experience ultimate comfort and sophistication in our luxurious hotel.')),
                ('our_facilities_title', models.CharField(default=' Where Luxury Meets Love', max_length=255)),
                ('our_facilities_subheading', models.TextField(default='State-of-the-art amenities designed to make your pets stay seamless, with luxury and convenience at every turn.')),
                ('our_services_title', models.CharField(default='Only The Best For Your Pets', max_length=255)),
                ('our_services_subheading', models.TextField(default='Exceptional service that goes above and beyond to cater to your pets every need.')),
                ('our_prices_title', models.CharField(default='Our Room Prices', max_length=255)),
                ('luxury_title', models.CharField(default='Luxury Like No Other', max_length=255)),
                ('luxury_subheading', models.TextField(default='Let your pet indulge in the finest amenities, elegant decor, and personalized experiences.')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hotel.hotelpage')),
            ],
            options={
                'verbose_name': 'Hotel Page Content Translation',
                'db_table': 'hotel_hotelpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServicePageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('hero_title', models.CharField(default='Our Services', max_length=200)),
                ('hero_subheading', models.CharField(default="Providing the best care for your pets while you're away.", max_length=300)),
                ('our_hotel_title', models.CharField(default='Our Pet Hotel', max_length=200)),
                ('our_hotel_subheading', models.TextField(default='Our pet hotel offers a safe and comfortable environment for your pets. With spacious rooms, loving staff, and 24/7 care, your pet will feel right at home.')),
                ('our_meal_title', models.CharField(default='Healthy Meals for Your Pet', max_length=200)),
                ('our_meal_subheading', models.TextField(default="We offer a variety of nutritious meals tailored to your pet's needs, ensuring they stay healthy and energized during their stay with us.")),
                ('our_training_title', models.CharField(default='Professional Pet Training', max_length=200)),
                ('our_training_subheading', models.TextField(default='Our professional trainers provide personalized training sessions to ensure your pet’s obedience and good behavior.')),
                ('our_grooming_title', models.CharField(default='Grooming Services', max_length=200)),
                ('our_grooming_subheading', models.TextField(default='Pamper your pet with our grooming services, including baths, trims, and nail care, to keep them looking and feeling their best.')),
                ('our_watersports_title', models.CharField(default='Exciting Water Sports', max_length=200)),
                ('our_watersports_subheading', models.TextField(default='Let your pet enjoy fun-filled water activities that are both stimulating and enjoyable, keeping them active and happy.')),
                ('our_transportation_title', models.CharField(default='Safe and Comfortable Transportation', max_length=200)),
                ('our_transportation_subheading', models.TextField(default='We offer transportation services to pick up and drop off your pet, ensuring they travel safely and comfortably to and from our hotel.')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hotel.servicepage')),
            ],
            options={
                'verbose_name': 'All Services Page Content Translation',
                'db_table': 'hotel_servicepage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
