# Generated by Django 5.1.7 on 2025-04-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='hotel/')),
                ('hero_title', models.CharField(default='Welcome to Your Luxury Stay', max_length=255)),
                ('hero_subheading', models.TextField(default='Experience ultimate comfort and sophistication in every corner of our luxurious hotel.')),
                ('our_facilities_title', models.CharField(default='Our Facilities', max_length=255)),
                ('our_facilities_subheading', models.TextField(default='State-of-the-art amenities designed to make your stay seamless, with luxury and convenience at every turn.')),
                ('our_facilities_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='hotel/')),
                ('our_services_title', models.CharField(default='Our Services', max_length=255)),
                ('our_services_subheading', models.TextField(default='Exceptional service that goes above and beyond to cater to your every need during your stay.')),
                ('our_services_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='hotel/')),
                ('luxury_title', models.CharField(default='Luxury Like No Other', max_length=255)),
                ('luxury_subheading', models.TextField(default='Indulge in the finest amenities, elegant decor, and personalized experiences that ensure your stay is unforgettable.')),
            ],
        ),
    ]
