# Generated by Django 5.1.7 on 2025-04-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpage',
            name='our_prices_subheading',
            field=models.TextField(default='Our exclusive accommodations provide comfort and luxury for yourpet, ensuring a relaxing stay. Choose the best option for your furry companion and experience the finest care.'),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='our_prices_title',
            field=models.CharField(default='Our Room Prices', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='hero_subheading',
            field=models.TextField(default='Let Your Pet Experience ultimate comfort and sophistication in our luxurious hotel.'),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='hero_title',
            field=models.CharField(default='Your Pets Luxury Stay', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='luxury_subheading',
            field=models.TextField(default='Let your pet indulge in the finest amenities, elegant decor, and personalized experiences.'),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='our_facilities_subheading',
            field=models.TextField(default='State-of-the-art amenities designed to make your pets stay seamless, with luxury and convenience at every turn.'),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='our_facilities_title',
            field=models.CharField(default=' Where Luxury Meets Love', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='our_services_subheading',
            field=models.TextField(default='Exceptional service that goes above and beyond to cater to your pets every need.'),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='our_services_title',
            field=models.CharField(default='Only The Best For Your Pets', max_length=255),
        ),
    ]
