# Generated by Django 5.1.7 on 2025-04-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='hero_image',
            field=models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='services/'),
        ),
    ]
