# Generated by Django 5.1.7 on 2025-04-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotelpage_our_prices_subheading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome to Our Pet Hotel', max_length=200)),
                ('hero_subheading', models.CharField(default="Providing the best care for your pets while you're away.", max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('our_hotel_title', models.CharField(default='Our Pet Hotel', max_length=200)),
                ('our_hotel_subheading', models.TextField(default='Our pet hotel offers a safe and comfortable environment for your pets. With spacious rooms, loving staff, and 24/7 care, your pet will feel right at home.')),
                ('our_hotel_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('our_meal_title', models.CharField(default='Healthy Meals for Your Pet', max_length=200)),
                ('our_meal_subheading', models.TextField(default="We offer a variety of nutritious meals tailored to your pet's needs, ensuring they stay healthy and energized during their stay with us.")),
                ('our_meal_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('our_training_title', models.CharField(default='Professional Pet Training', max_length=200)),
                ('our_training_subheading', models.TextField(default='Our professional trainers provide personalized training sessions to ensure your pet’s obedience and good behavior.')),
                ('our_training_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('our_grooming_title', models.CharField(default='Grooming Services', max_length=200)),
                ('our_grooming_subheading', models.TextField(default='Pamper your pet with our grooming services, including baths, trims, and nail care, to keep them looking and feeling their best.')),
                ('our_grooming_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('our_watersports_title', models.CharField(default='Exciting Water Sports', max_length=200)),
                ('our_watersports_subheading', models.TextField(default='Let your pet enjoy fun-filled water activities that are both stimulating and enjoyable, keeping them active and happy.')),
                ('our_watersports_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('our_transportation_title', models.CharField(default='Safe and Comfortable Transportation', max_length=200)),
                ('our_transportation_subheading', models.TextField(default='We offer transportation services to pick up and drop off your pet, ensuring they travel safely and comfortably to and from our hotel.')),
                ('our_transportation_image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='our_prices_subheading',
            field=models.TextField(default='Our exclusive accommodations provide comfort and luxury for your pet, ensuring a relaxing stay. Choose the best option for your furry companion and experience the finest care.'),
        ),
    ]
