# Generated by Django 5.1.7 on 2025-04-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_servicepage_alter_hotelpage_our_prices_subheading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='hero_image',
            field=models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='hero_title',
            field=models.CharField(default='Our Services', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='our_grooming_image',
            field=models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='our_hotel_image',
            field=models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='our_meal_image',
            field=models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='our_training_image',
            field=models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='our_transportation_image',
            field=models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='our_watersports_image',
            field=models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='services/'),
        ),
    ]
