# Generated by Django 5.1.7 on 2025-04-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_servicepage_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelpage',
            options={'verbose_name': 'Hotel Page', 'verbose_name_plural': 'Hotel Page'},
        ),
        migrations.AlterModelOptions(
            name='servicepage',
            options={'verbose_name': 'All Services Page', 'verbose_name_plural': 'All Services Page'},
        ),
    ]
