# Generated by Django 5.1.7 on 2025-04-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotelpage_options_alter_servicepage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelpage',
            options={'verbose_name': 'Hotel Page Content', 'verbose_name_plural': 'Hotel Page Content'},
        ),
        migrations.AlterModelOptions(
            name='servicepage',
            options={'verbose_name': 'All Services Page Content', 'verbose_name_plural': 'All Services Page Content'},
        ),
    ]
