# Generated by Django 5.1.7 on 2025-04-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Your Company Name', help_text='Enter the full name of the company.', max_length=255)),
                ('company_email', models.EmailField(default='contact@company.com', help_text='Enter the official company email address.', max_length=254)),
                ('company_phone', models.CharField(default='+1-555-000-0000', help_text='Enter the company’s contact number (e.g., +1-555-000-0000).', max_length=20)),
                ('company_address', models.TextField(default='123 Street Name, City, Country, ZIP', help_text='Enter the full address of the company, including city and ZIP code.')),
                ('logo', models.ImageField(default='default/default_logo.png', help_text='Upload the website logo.', upload_to='branding/')),
                ('favicon', models.ImageField(default='default/default_icon.ico', help_text='Upload the favicon (ICO or PNG).', upload_to='branding/')),
                ('video', models.FileField(blank=True, default='default/default_video.mp4', help_text='Upload a promotional or branding video file.', null=True, upload_to='branding/videos/')),
                ('meta_keywords', models.CharField(blank=True, default='generic, branding, business, website, company', help_text='Enter meta keywords for SEO (comma-separated).', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='Enter a meta description for SEO.', help_text='Enter a meta description for SEO.')),
                ('twitter_link', models.URLField(blank=True, default='https://twitter.com/yourcompany', help_text='Link to your Twitter profile.')),
                ('facebook_link', models.URLField(blank=True, default='https://facebook.com/yourcompany', help_text='Link to your Facebook page.')),
                ('instagram_link', models.URLField(blank=True, default='https://instagram.com/yourcompany', help_text='Link to your Instagram profile.')),
            ],
            options={
                'verbose_name': 'Branding',
                'verbose_name_plural': 'Branding',
            },
        ),
    ]
