# Generated by Django 5.1.7 on 2025-04-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Enter the full name of the company.', max_length=255)),
                ('company_email', models.EmailField(help_text='Enter the official company email address.', max_length=254)),
                ('company_phone', models.CharField(help_text='Enter the company’s contact number (e.g., +1-234-567-8901).', max_length=20)),
                ('company_address', models.CharField(help_text='Enter the full address of the company, including city and ZIP code.', max_length=255)),
                ('logo', models.ImageField(default='default/logo.png', help_text='Upload the website logo.', upload_to='branding/')),
                ('favicon', models.ImageField(default='default/favicon.ico', help_text='Upload the favicon (ICO or PNG).', upload_to='branding/')),
            ],
        ),
    ]
