# Generated by Django 5.1.7 on 2025-04-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='facebook_link',
            field=models.URLField(blank=True, help_text='Link to your Facebook page.'),
        ),
        migrations.AddField(
            model_name='branding',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Link to your Instagram profile.'),
        ),
        migrations.AddField(
            model_name='branding',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Enter a meta description for SEO.'),
        ),
        migrations.AddField(
            model_name='branding',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Enter meta keywords for SEO (comma-separated).', max_length=255),
        ),
        migrations.AddField(
            model_name='branding',
            name='twitter_link',
            field=models.URLField(blank=True, help_text='Link to your Twitter profile.'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='favicon',
            field=models.ImageField(help_text='Upload the favicon (ICO or PNG).', upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='logo',
            field=models.ImageField(help_text='Upload the website logo.', upload_to='branding/'),
        ),
    ]
