# Generated by Django 5.1.7 on 2025-04-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_branding_facebook_link_branding_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branding',
            name='company_address',
            field=models.TextField(default='123 Street Name, City, Country, ZIP', help_text='Enter the full address of the company, including city and ZIP code.'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='company_email',
            field=models.EmailField(default='contact@company.com', help_text='Enter the official company email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='branding',
            name='company_name',
            field=models.CharField(default='Your Company Name', help_text='Enter the full name of the company.', max_length=255),
        ),
        migrations.AlterField(
            model_name='branding',
            name='company_phone',
            field=models.CharField(default='+1-555-000-0000', help_text='Enter the company’s contact number (e.g., +1-555-000-0000).', max_length=20),
        ),
        migrations.AlterField(
            model_name='branding',
            name='facebook_link',
            field=models.URLField(blank=True, default='https://facebook.com/yourcompany', help_text='Link to your Facebook page.'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='favicon',
            field=models.ImageField(default='default/default_icon.ico', help_text='Upload the favicon (ICO or PNG).', upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='instagram_link',
            field=models.URLField(blank=True, default='https://instagram.com/yourcompany', help_text='Link to your Instagram profile.'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='logo',
            field=models.ImageField(default='default/default_logo.png', help_text='Upload the website logo.', upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='meta_description',
            field=models.TextField(blank=True, default='Enter a meta description for SEO.', help_text='Enter a meta description for SEO.'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='meta_keywords',
            field=models.CharField(blank=True, default='generic, branding, business, website, company', help_text='Enter meta keywords for SEO (comma-separated).', max_length=255),
        ),
        migrations.AlterField(
            model_name='branding',
            name='twitter_link',
            field=models.URLField(blank=True, default='https://twitter.com/yourcompany', help_text='Link to your Twitter profile.'),
        ),
    ]
