# Generated by Django 5.1.7 on 2025-04-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0003_alter_branding_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='video',
            field=models.FileField(blank=True, default='default/default_video.mp4', help_text='Upload a promotional or branding video file.', null=True, upload_to='branding/videos/'),
        ),
    ]
