# Generated by Django 5.1.7 on 2025-04-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0004_branding_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branding',
            options={'verbose_name': 'Branding', 'verbose_name_plural': 'Branding'},
        ),
    ]
