# Generated by Django 5.1.7 on 2025-04-07 20:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grooming', '0001_initial'),
        ('meals', '0001_initial'),
        ('training', '0001_initial'),
        ('water_sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overall discount for all rooms (as a percentage).', max_digits=5)),
                ('multipet_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount for bookings with multiple pets (as a percentage).', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=50)),
                ('pet_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('number_of_pets', models.IntegerField()),
                ('pet_details', models.JSONField()),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('selected_grooming_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grooming.service')),
                ('selected_meal_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.service')),
                ('selected_training_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.service')),
                ('selected_water_sports_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='water_sports.service')),
            ],
        ),
    ]
