# Generated by Django 5.1.7 on 2025-04-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='check_in_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out',
            new_name='check_out_date',
        ),
    ]
