# Generated by Django 5.1.7 on 2025-04-02 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_check_in_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('small_dog', 'Small Dog'), ('medium_dog', 'Medium Dog'), ('large_dog', 'Large Dog'), ('small_cat', 'Small Cat'), ('medium_cat', 'Medium Cat'), ('large_cat', 'Large Cat')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_grooming_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_meal_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_training_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_water_sports_service',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BookingTotalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pets', models.PositiveIntegerField(default=1)),
                ('pet_details', models.TextField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.pettype')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_for_additional_pet', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_prices', to='booking.pettype')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_prices', to='booking.room')),
            ],
        ),
    ]
