# Generated by Django 5.1.7 on 2025-04-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_pettype_remove_booking_room_booking_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=50)),
                ('pet_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookingtotalprice',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='roomprice',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='roomprice',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='pet_details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.room'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookingRoom',
        ),
        migrations.DeleteModel(
            name='BookingTotalPrice',
        ),
        migrations.DeleteModel(
            name='PetType',
        ),
        migrations.DeleteModel(
            name='RoomPrice',
        ),
    ]
