# Generated by Django 5.1.7 on 2025-04-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_roomprices_remove_bookingtotalprice_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprices',
            name='pet_size',
            field=models.CharField(choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roomprices',
            name='pet_type',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], max_length=50),
        ),
    ]
