# Generated by Django 5.1.7 on 2025-04-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_roomprices_pet_size_alter_roomprices_pet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprices',
            name='pet_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50),
        ),
    ]
