# Generated by Django 5.1.7 on 2025-04-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_roomprices_pet_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprices',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=50),
        ),
    ]
