# Generated by Django 5.1.7 on 2025-04-02 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_roomprices_pet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pet_details',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_pets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255)),
                ('pet_type', models.CharField(max_length=100)),
                ('pet_size', models.CharField(max_length=100)),
                ('pet_breed', models.CharField(max_length=100)),
                ('pet_requirements', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='booking.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='booking.room')),
            ],
        ),
    ]
