# Generated by Django 5.1.7 on 2025-04-03 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_booking_pet_details_remove_booking_room_and_more'),
        ('grooming', '0005_alter_animalsize_animal_alter_animalsize_size'),
        ('meals', '0003_alter_animalsize_animal'),
        ('training', '0002_service_duration_service_price_delete_animalsize'),
        ('water_sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='selected_grooming_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grooming_service', to='grooming.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_meal_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_service', to='meals.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_training_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_service', to='training.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_water_sports_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_sports_service', to='water_sports.service'),
        ),
    ]
