# Generated by Django 5.1.7 on 2025-04-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_selected_grooming_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='pet_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
