# Generated by Django 5.1.7 on 2025-04-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_booking_user_name_booking_pet_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
