# Generated by Django 5.1.7 on 2025-04-03 11:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_pickup_address'),
        ('grooming', '0005_alter_animalsize_animal_alter_animalsize_size'),
        ('meals', '0003_alter_animalsize_animal'),
        ('training', '0002_service_duration_service_price_delete_animalsize'),
        ('water_sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='extra_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_pets',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pet_details',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_grooming_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grooming.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_meal_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_training_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_water_sports_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='water_sports.service'),
        ),
    ]
