# Generated by Django 5.1.7 on 2025-04-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_booking_created_at_booking_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pickup_address',
            field=models.TextField(),
        ),
    ]
