# Generated by Django 5.1.7 on 2025-04-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_booking_pickup_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
