# Generated by Django 5.1.7 on 2025-04-03 13:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_booking_extra_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overall discount for all rooms (as a percentage).', max_digits=5)),
                ('multipet_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount for bookings with multiple pets (as a percentage).', max_digits=5)),
            ],
        ),
    ]
