# Generated by Django 5.1.7 on 2025-04-07 20:04

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_per_mile', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Prices',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='TransportationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='transportation/')),
                ('our_transportation_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='transportation/')),
            ],
            options={
                'verbose_name': 'Transportation Page Content',
                'verbose_name_plural': 'Transportation Page Content',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TransportationPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('hero_title', models.CharField(default='Reliable Pet Transportation Services', max_length=100, verbose_name='Hero Title')),
                ('hero_subheading', models.CharField(default='Safe, comfortable, and stress-free travel for your beloved pets—wherever they need to go.', max_length=255, verbose_name='Hero Subheading')),
                ('our_transportation_title', models.CharField(default='Comfort & Care on the Move', max_length=100, verbose_name='Our Transportation Title')),
                ('our_transportation_subheading', models.TextField(default='Our experienced team ensures every journey is smooth, whether it’s a trip to the vet, airport, or a new home.', verbose_name='Our Transportation Subheading')),
                ('transportation_info_title', models.CharField(default='Services & Routes', max_length=100, verbose_name='Transportation Info Title')),
                ('training_info_description', models.TextField(default='We offer one-way or round-trip transportation options, customizable based on your pet’s needs. Long-distance and local trips available.', verbose_name='Transportation Info Description')),
                ('cta_title', models.CharField(default='Book Safe Pet Travel Today', max_length=100, verbose_name='CTA Title')),
                ('cta_subheading', models.TextField(default='Schedule a ride and travel with peace of mind. Our pet-friendly vehicles and trained staff are ready to help.', verbose_name='CTA Subheading')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='transportation.transportationpage')),
            ],
            options={
                'verbose_name': 'Transportation Page Content Translation',
                'db_table': 'transportation_transportationpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
