# Generated by Django 5.1.7 on 2025-04-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_alter_transportation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Reliable Pet Transportation Services', max_length=100)),
                ('hero_subheading', models.CharField(default='Safe, comfortable, and stress-free travel for your beloved pets—wherever they need to go.', max_length=255)),
                ('hero_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='transportation/')),
                ('our_training_title', models.CharField(default='Comfort & Care on the Move', max_length=100)),
                ('our_training_subheading', models.TextField(default='Our experienced team ensures every journey is smooth, whether it’s a trip to the vet, airport, or a new home.')),
                ('our_training_image', models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='transportation/')),
                ('training_info_title', models.CharField(default='Services & Routes', max_length=100)),
                ('training_info_description', models.TextField(default='We offer one-way or round-trip transportation options, customizable based on your pet’s needs. Long-distance and local trips available.')),
                ('cta_title', models.CharField(default='Book Safe Pet Travel Today', max_length=100)),
                ('cta_subheading', models.TextField(default='Schedule a ride and travel with peace of mind. Our pet-friendly vehicles and trained staff are ready to help.')),
            ],
            options={
                'verbose_name': 'Transportation Page Content',
                'verbose_name_plural': 'Transportation Page Content',
            },
        ),
        migrations.RenameModel(
            old_name='Transportation',
            new_name='Service',
        ),
    ]
