# Generated by Django 5.1.7 on 2025-04-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_transportationpage_rename_transportation_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportationpage',
            old_name='our_training_image',
            new_name='our_transportation_image',
        ),
        migrations.RenameField(
            model_name='transportationpage',
            old_name='our_training_subheading',
            new_name='our_transportation_subheading',
        ),
        migrations.RenameField(
            model_name='transportationpage',
            old_name='our_training_title',
            new_name='our_transportation_title',
        ),
        migrations.RenameField(
            model_name='transportationpage',
            old_name='training_info_title',
            new_name='transportation_info_title',
        ),
    ]
