# Generated by Django 5.1.7 on 2025-04-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='image',
            field=models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='contact/'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='subheading',
            field=models.CharField(blank=True, default='We’d love to hear from you! Feel free to reach out with any questions or inquiries.', max_length=255),
        ),
    ]
