# Generated by Django 5.1.7 on 2025-04-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactpage_image_alter_contactpage_subheading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact Page', 'verbose_name_plural': 'Contact Page'},
        ),
    ]
