# Generated by Django 5.1.7 on 2025-04-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact Page Content', 'verbose_name_plural': 'Contact Page Content'},
        ),
    ]
